language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t idalavye/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true idalavye/docker-react npm run test